### PR TITLE
Displacement & Other Simulator Fixes

### PR DESCRIPTION
**Pull request by WonderlandWar**
This fixes displacements and improves the fix for nonsolid static props. I wasn't able to compile this without crashes (even before all of my changes), so you may need to do testing yourself before officially using this.

### CODE REVIEW

**Comment by SonicEraZoR** [comment]
Well, sorry to disappoint but it doesn't work if you place a portal on a displacement, you can't actually go through a portal.

The improved fix for non solid static props does make sense though. I can just copy the code from the pull request and commit it myself (and give you credit) or you can make separate pull request just for it.

**Comment by WonderlandWar** [comment]
You could include the fix, but keep it as a convar, it's enabled by default, "portal_clone_displacements".

**Comment by SonicEraZoR** [comment]
I don't see a point in including non fully working fix even if it's hidden behind a con var

**Comment by MyGamepedia** [comment]
We recently discussed this issue and came to the conclusion that we won't be adding portal cutting into the displays, as no one has been able to implement a stable solution. We'll prevent placing portals on the displays. So this pr or Bunny's version will be merged (questions about this to him). I'd also like to use some of code from Portal Coop, portals in your version feel very smooth.

**Pull request closed without merging**
